version: 2.1
orbs:
  node: circleci/node@3.0.0
  
jobs:
  hello-world:
    docker: 
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: echo "Hello World"
  test:
    docker:
      - image: cimg/node:16:0:0
    steps:
      - checkout
      - run: npm test

workflows:
  node-tests:
    jobs:
      - hello-world
      - test
