version: 2.1

jobs:
  hello-world:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: echo "hello world"

orbs:
  node: circleci/node@3.0.0
workflows:
  hello-world:
    jobs:
      - hello-world
  node-tests:
    jobs:
      - node/test

